/**
 * Country and province/state data for shipping rate geo-restrictions.
 * Covers the most commonly used Shopify merchant countries with their subdivisions.
 */
import type { CountryOption } from "@/components/form-builder/shipping-rates-types";

export const SHIPPING_COUNTRIES: CountryOption[] = [
  {
    code: "US",
    name: "United States",
    provinces: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" },
    ],
  },
  {
    code: "CA",
    name: "Canada",
    provinces: [
      { code: "AB", name: "Alberta" },
      { code: "BC", name: "British Columbia" },
      { code: "MB", name: "Manitoba" },
      { code: "NB", name: "New Brunswick" },
      { code: "NL", name: "Newfoundland and Labrador" },
      { code: "NS", name: "Nova Scotia" },
      { code: "ON", name: "Ontario" },
      { code: "PE", name: "Prince Edward Island" },
      { code: "QC", name: "Quebec" },
      { code: "SK", name: "Saskatchewan" },
      { code: "NT", name: "Northwest Territories" },
      { code: "NU", name: "Nunavut" },
      { code: "YT", name: "Yukon" },
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    provinces: [
      { code: "ENG", name: "England" },
      { code: "SCT", name: "Scotland" },
      { code: "WLS", name: "Wales" },
      { code: "NIR", name: "Northern Ireland" },
    ],
  },
  {
    code: "AU",
    name: "Australia",
    provinces: [
      { code: "NSW", name: "New South Wales" },
      { code: "VIC", name: "Victoria" },
      { code: "QLD", name: "Queensland" },
      { code: "WA", name: "Western Australia" },
      { code: "SA", name: "South Australia" },
      { code: "TAS", name: "Tasmania" },
      { code: "ACT", name: "Australian Capital Territory" },
      { code: "NT", name: "Northern Territory" },
    ],
  },
  {
    code: "DE",
    name: "Germany",
    provinces: [
      { code: "BW", name: "Baden-Württemberg" },
      { code: "BY", name: "Bavaria" },
      { code: "BE", name: "Berlin" },
      { code: "BB", name: "Brandenburg" },
      { code: "HB", name: "Bremen" },
      { code: "HH", name: "Hamburg" },
      { code: "HE", name: "Hesse" },
      { code: "NI", name: "Lower Saxony" },
      { code: "MV", name: "Mecklenburg-Vorpommern" },
      { code: "NW", name: "North Rhine-Westphalia" },
      { code: "RP", name: "Rhineland-Palatinate" },
      { code: "SL", name: "Saarland" },
      { code: "SN", name: "Saxony" },
      { code: "ST", name: "Saxony-Anhalt" },
      { code: "SH", name: "Schleswig-Holstein" },
      { code: "TH", name: "Thuringia" },
    ],
  },
  {
    code: "FR",
    name: "France",
    provinces: [],
  },
  {
    code: "IN",
    name: "India",
    provinces: [
      { code: "AP", name: "Andhra Pradesh" },
      { code: "AR", name: "Arunachal Pradesh" },
      { code: "AS", name: "Assam" },
      { code: "BR", name: "Bihar" },
      { code: "CT", name: "Chhattisgarh" },
      { code: "GA", name: "Goa" },
      { code: "GJ", name: "Gujarat" },
      { code: "HR", name: "Haryana" },
      { code: "HP", name: "Himachal Pradesh" },
      { code: "JH", name: "Jharkhand" },
      { code: "KA", name: "Karnataka" },
      { code: "KL", name: "Kerala" },
      { code: "MP", name: "Madhya Pradesh" },
      { code: "MH", name: "Maharashtra" },
      { code: "MN", name: "Manipur" },
      { code: "ML", name: "Meghalaya" },
      { code: "MZ", name: "Mizoram" },
      { code: "NL", name: "Nagaland" },
      { code: "OR", name: "Odisha" },
      { code: "PB", name: "Punjab" },
      { code: "RJ", name: "Rajasthan" },
      { code: "SK", name: "Sikkim" },
      { code: "TN", name: "Tamil Nadu" },
      { code: "TG", name: "Telangana" },
      { code: "TR", name: "Tripura" },
      { code: "UP", name: "Uttar Pradesh" },
      { code: "UT", name: "Uttarakhand" },
      { code: "WB", name: "West Bengal" },
      { code: "DL", name: "Delhi" },
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    provinces: [
      { code: "AZ", name: "Abu Dhabi" },
      { code: "AJ", name: "Ajman" },
      { code: "DU", name: "Dubai" },
      { code: "FU", name: "Fujairah" },
      { code: "RK", name: "Ras Al Khaimah" },
      { code: "SH", name: "Sharjah" },
      { code: "UQ", name: "Umm Al Quwain" },
    ],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    provinces: [
      { code: "01", name: "Riyadh" },
      { code: "02", name: "Makkah" },
      { code: "03", name: "Madinah" },
      { code: "04", name: "Eastern Province" },
      { code: "06", name: "Asir" },
      { code: "07", name: "Tabuk" },
      { code: "08", name: "Hail" },
      { code: "09", name: "Northern Borders" },
      { code: "10", name: "Jazan" },
      { code: "11", name: "Najran" },
      { code: "12", name: "Al Bahah" },
      { code: "05", name: "Qassim" },
      { code: "14", name: "Al Jawf" },
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    provinces: [
      { code: "PB", name: "Punjab" },
      { code: "SD", name: "Sindh" },
      { code: "KP", name: "Khyber Pakhtunkhwa" },
      { code: "BA", name: "Balochistan" },
      { code: "IS", name: "Islamabad" },
      { code: "GB", name: "Gilgit-Baltistan" },
      { code: "AK", name: "Azad Kashmir" },
    ],
  },
  { code: "JP", name: "Japan", provinces: [] },
  { code: "BR", name: "Brazil", provinces: [] },
  { code: "MX", name: "Mexico", provinces: [] },
  { code: "IT", name: "Italy", provinces: [] },
  { code: "ES", name: "Spain", provinces: [] },
  { code: "NL", name: "Netherlands", provinces: [] },
  { code: "SE", name: "Sweden", provinces: [] },
  { code: "NO", name: "Norway", provinces: [] },
  { code: "NZ", name: "New Zealand", provinces: [] },
  { code: "SG", name: "Singapore", provinces: [] },
  { code: "MY", name: "Malaysia", provinces: [] },
  { code: "PH", name: "Philippines", provinces: [] },
  { code: "EG", name: "Egypt", provinces: [] },
  { code: "NG", name: "Nigeria", provinces: [] },
  { code: "ZA", name: "South Africa", provinces: [] },
  { code: "KR", name: "South Korea", provinces: [] },
  { code: "TR", name: "Turkey", provinces: [] },
  { code: "PL", name: "Poland", provinces: [] },
  { code: "CH", name: "Switzerland", provinces: [] },
  { code: "AT", name: "Austria", provinces: [] },
  { code: "IE", name: "Ireland", provinces: [] },
  { code: "DK", name: "Denmark", provinces: [] },
  { code: "FI", name: "Finland", provinces: [] },
  { code: "PT", name: "Portugal", provinces: [] },
  { code: "IL", name: "Israel", provinces: [] },
  { code: "QA", name: "Qatar", provinces: [] },
  { code: "KW", name: "Kuwait", provinces: [] },
  { code: "BH", name: "Bahrain", provinces: [] },
  { code: "OM", name: "Oman", provinces: [] },
];
