# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e41060c8d2fb8abbc90ae3d1fc42455a"
name = "BuyEase COD Form"
application_url = "https://buyease-merchant-4st4.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [
    "orders/create",
    "orders/updated",
    "app/uninstalled",
    "app_subscriptions/update",
  ]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]
  uri = "/api/webhooks"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://buyease-merchant-4st4.vercel.app/api/auth",
  "https://buyease-merchant-4st4.vercel.app/api/auth/callback"
]
