name = "COD Form & Upsells"
client_id = ""
application_url = "https://buyease-merchant-4st4.vercel.app"
embedded = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_products,write_products,write_orders,read_orders,read_customers,write_customers,read_script_tags,write_script_tags"
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/api/webhooks"
